sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '4'
  - stable
after_success: >-
  travis-after-all && npm run semantic-release && npm run pages -- --repo
  https://${GH_TOKEN}@github.com/the-economist-editorial/component-silver-tab-bar.git
